### ISSUE TITLE
Bumping aws sdk version v2

### ISSUE THREAD

**Issue by ratoshniuk** [scanamo/scanamo#333] opened 2019-01-31 08:10 UTC
Hi there!

I am currently working on dynamo db wrapping but I found this library and its API looks pretty good. BUT!
Amazon published new API https://github.com/aws/aws-sdk-java-v2
What about "bumping" to this version? 

I currently working on with that instead of writing yet another wrapper for dynamo

**Comment by regiskuckaertz** [comment] 2019-01-31 09:46
Hi @ratoshniuk ! yes, v2 has been on my mind for some time. To be honest I did no plan for it before we release v1, which is pending a couple of bug fixes now. But if you have appetite for porting it over, by all means 🤗 That would be very much appreciated 😗

**Comment by ratoshniuk** [comment] 2019-01-31 09:59
@regiskuckaertz cool! stay tuned with my PR !

**Comment by ratoshniuk** [comment] 2019-02-03 10:04
Hi there! I made a migration **EXCEPT** alpakka. 

They currently have an open issue for migration sdk (I am also referenced for that) and I don't actually known how to work with alpaca interop.

We can make wrappers between v1 and v2 api. Do you have any ideas?

**Comment by ratoshniuk** [comment] 2019-02-03 10:07
Anyway, can somebody check my PR and request changes if needs? Thank you!

**Comment by regiskuckaertz** [comment] 2019-02-03 11:20
Thank you for this. I'll have a look asap.

**Comment by regiskuckaertz** [comment] 2019-04-17 13:59
Duplicate of #287

**Closed by regiskuckaertz** 2019-04-17 13:59 UTC
